mandatoryAccounts:
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this
      mandatory account. Note, the account name key does not need to match the
      AWS account name.
    email: someexamplelztest@gmail.com
    organizationalUnit: Root
    warm: false
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory
      account. Note, the account name key does not need to match the AWS account
      name.
    email: someexamplelztest+new-logs@gmail.com
    organizationalUnit: Security
    warm: false
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not
      change the name field for this mandatory account. Note, the account name
      key does not need to match the AWS account name.
    email: someexamplelztest+new-audit@gmail.com
    organizationalUnit: Security
    warm: false
workloadAccounts:
  - name: Network
    description: The shared network account is used for shared networking resources. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: someexamplelztest+new-network@gmail.com
    organizationalUnit: Infrastructure
  - name: SomeEnvProduction
    description: The SomeEnv Production account is used for the SomeEnv Production environment. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: someexamplelztest+new-SomeEnv-production@gmail.com
    organizationalUnit: SomeEnv/Production
