mandatoryAccounts:
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this
      mandatory account. Note, the account name key does not need to match the
      AWS account name.
    email: bjsslztest@gmail.com
    organizationalUnit: Root
    warm: false
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory
      account. Note, the account name key does not need to match the AWS account
      name.
    email: bjsslztest+new-logs@gmail.com
    organizationalUnit: Security
    warm: false
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not
      change the name field for this mandatory account. Note, the account name
      key does not need to match the AWS account name.
    email: bjsslztest+new-audit@gmail.com
    organizationalUnit: Security
    warm: false
workloadAccounts:
  - name: Network
    description: The shared network account is used for shared networking resources. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: bjsslztest+new-network@gmail.com
    organizationalUnit: Infrastructure
  - name: PortalDevelopment
    description: The Portal Development account is used for the Portal Development environment. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: bjsslztest+new-portal-development@gmail.com
    organizationalUnit: Portal/Development
  - name: PortalStaging
    description: The Portal Staging account is used for the Portal Staging environment. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: bjsslztest+new-portal-staging@gmail.com
    organizationalUnit: Portal/Staging
  - name: PortalProduction
    description: The Portal Production account is used for the Portal Production environment. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: bjsslztest+new-portal-production@gmail.com
    organizationalUnit: Portal/Production
  #customer accounts
  - name: Customer123
    description: Customer123 account.
    email: bjsslztest+new-customer123@gmail.com
    organizationalUnit: Customer/Accounts
