customizations:
  cloudFormationStackSets:
    - capabilities:
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_AUTO_EXPAND
        - CAPABILITY_IAM
        - CAPABILITY_AUTO_EXPAND
      deploymentTargets:
        organizationalUnits:
          - Portal
      regions:
        - ap-southeast-2
      template: customizations/github-oicd-provider.yaml
      name: GitHubOICDProvider
