homeRegion: ap-southeast-2
configVersion: 1.11.2-a
enabledRegions:
  - ap-southeast-2
managementAccountAccessRole: AWSControlTowerExecution
cloudwatchLogRetentionInDays: 3653
cdkOptions:
  centralizeBuckets: true
  useManagementAccessRole: true
terminationProtection: true
enableOptInRegions: false
snsTopics:
  deploymentTargets:
    accounts:
      - Management
      - Audit
  topics:
    - name: SecurityHigh
      emailAddresses:
        - "{{ SecurityHigh }}"
    - name: SecurityMedium
      emailAddresses:
        - "{{ SecurityMedium }}"
    - name: SecurityLow
      emailAddresses:
        - "{{ SecurityLow }}"
    - name: SecurityIgnore
      emailAddresses:
        - "{{ SecurityIgnore }}"
controlTower:
  enable: true
  landingZone:
    version: '3.3'
    logging:
      loggingBucketRetentionDays: 365
      accessLoggingBucketRetentionDays: 3650
      organizationTrail: true
    security:
      enableIdentityCenterAccess: true
  controls: []
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
    organizationTrailSettings:
      multiRegionTrail: true
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: true
      lambdaDataEvents: true
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
    accountTrails: []
    lifecycleRules: []
  sessionManager:
    sendToCloudWatchLogs: true
    sendToS3: true
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 730
        noncurrentVersionExpiration: 730
    attachPolicyToIamRoles:
      - EC2-Default-SSM-AD-Role
      - RDGW-Role
      - Rsyslog-Role
    excludeAccounts:
      - Management
      - LogArchive
      - Audit
  cloudwatchLogs:
    dynamicPartitioning: dynamic-partitioning/log-filters.json
    exclusions:
      - accounts:
          - Management
        logGroupNames:
          - aws-accelerator-cloudtrail-logs
    encryption:
      useCMK: true
      deploymentTargets:
        organizationalUnits:
          - Security
          - Infrastructure
          - Central
          - Dev
          - Test
          - Prod
          - UnClass
          - Sandbox
        accounts:
          - Management
  accessLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 730
        noncurrentVersionExpiration: 730
  centralLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 730
        noncurrentVersionExpiration: 730
  elbLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 730
        noncurrentVersionExpiration: 730
tags: []
iamRoleSsmParameters: []
s3:
  encryption:
    createCMK: true
    deploymentTargets:
      organizationalUnits:
        - Security
        - Infrastructure
        - Central
        - Dev
        - Test
        - Prod
        - UnClass
        - Sandbox
      accounts:
        - Management
lambda:
  encryption:
    useCMK: true
    deploymentTargets:
      organizationalUnits:
        - Security
        - Infrastructure
        - Central
        - Dev
        - Test
        - Prod
        - UnClass
        - Sandbox
      accounts:
        - Management
ssmInventory:
  enable: true
  deploymentTargets:
    organizationalUnits:
      - Infrastructure
      - Security
      - Central
      - Dev
      - Test
      - Prod
      - UnClass
      - Sandbox
reports:
  costAndUsageReport:
    compression: Parquet
    format: Parquet
    reportName: Cost-and-Usage-Report
    s3Prefix: cur
    timeUnit: HOURLY
    refreshClosedReports: true
    reportVersioning: OVERWRITE_REPORT
    additionalArtifacts:
      - ATHENA
    additionalSchemaElements:
      - RESOURCES
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 730
        noncurrentVersionExpiration: 730
  budgets:
    - deploymentTargets:
        accounts:
          - Network
      name: accel-budget
      timeUnit: MONTHLY
      type: COST
      amount: 2000
      includeUpfront: true
      includeTax: true
      includeSupport: true
      includeSubscription: true
      includeRecurring: true
      includeOtherSubscription: true
      includeDiscount: true
      includeCredit: false
      includeRefund: false
      useBlended: false
      useAmortized: false
      unit: USD
      notifications:
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 100
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 90
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 75
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 50
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
    - deploymentTargets:
        accounts:
          - Perimeter
      name: accel-budget
      timeUnit: MONTHLY
      type: COST
      amount: 2000
      includeUpfront: true
      includeTax: true
      includeSupport: true
      includeSubscription: true
      includeRecurring: true
      includeOtherSubscription: true
      includeDiscount: true
      includeCredit: false
      includeRefund: false
      useBlended: false
      useAmortized: false
      unit: USD
      notifications:
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 100
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 90
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 80
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 75
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 50
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
    - deploymentTargets:
        accounts:
          - Management
      name: accel-budget
      timeUnit: MONTHLY
      type: COST
      amount: 10000
      includeUpfront: true
      includeTax: true
      includeSupport: true
      includeSubscription: true
      includeRecurring: true
      includeOtherSubscription: true
      includeDiscount: true
      includeCredit: false
      includeRefund: false
      useBlended: false
      useAmortized: false
      unit: USD
      notifications:
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 100
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 90
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 80
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 75
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 50
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
    - deploymentTargets:
        organizationalUnits:
          - Security
          - Infrastructure
          - Central
          - Dev
          - Test
          - Prod
          - UnClass
          - Sandbox
      name: default-accel-budget
      timeUnit: MONTHLY
      type: COST
      amount: 1000
      includeUpfront: true
      includeTax: true
      includeSupport: true
      includeSubscription: true
      includeRecurring: true
      includeOtherSubscription: true
      includeDiscount: true
      includeCredit: false
      includeRefund: false
      useBlended: false
      useAmortized: false
      unit: USD
      notifications:
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 100
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 90
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 80
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 75
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 50
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: "{{ BudgetEmail }}"
limits:
  - serviceCode: vpc
    quotaCode: L-29B6F2EB
    desiredValue: 90
    deploymentTargets:
      accounts:
        - Network
  - serviceCode: vpc
    quotaCode: L-F678F1CE
    desiredValue: 15
    deploymentTargets:
      accounts:
        - Network
  - serviceCode: ec2
    quotaCode: L-0263D0A3
    desiredValue: 5
    deploymentTargets:
      accounts:
        - Perimeter

