homeRegion: ap-southeast-2
enabledRegions:
  - ap-southeast-2
managementAccountAccessRole: AWSControlTowerExecution
cloudwatchLogRetentionInDays: 3653
cdkOptions:
  centralizeBuckets: true
  useManagementAccessRole: true
terminationProtection: true
enableOptInRegions: false
controlTower:
  enable: true
  landingZone:
    version: '3.3'
    logging:
      loggingBucketRetentionDays: 365
      accessLoggingBucketRetentionDays: 3650
      organizationTrail: true
    security:
      enableIdentityCenterAccess: true
  controls: []
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
    organizationTrailSettings:
      multiRegionTrail: true
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: true
      lambdaDataEvents: true
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
    accountTrails: []
    lifecycleRules: []
  sessionManager:
    sendToCloudWatchLogs: true
    sendToS3: true
    excludeRegions: []
    excludeAccounts: []
    lifecycleRules: []
    attachPolicyToIamRoles: []
tags: []
snsTopics:
  deploymentTargets:
    accounts:
      - Management
      - Audit
  topics:
    - name: SecurityHigh
      emailAddresses:
        - "{{ SecurityHigh }}"
    - name: SecurityMedium
      emailAddresses:
        - "{{ SecurityMedium }}"
    - name: SecurityLow
      emailAddresses:
        - "{{ SecurityLow }}"
    - name: SecurityIgnore
      emailAddresses:
        - "{{ SecurityIgnore }}"
iamRoleSsmParameters: []
