providers: []
policySets: []
roleSets:
  - deploymentTargets:
      organizationalUnits:
        - Portal
    roles:
      - name: CI-Role-Developer
        assumedBy:
          - type: service
            principal: codebuild.amazonaws.com
        policies:
          awsManaged:
            - PowerUserAccess
groupSets: []
userSets: []
identityCenter:
  name: tnhtnhtnhexample
  delegatedAdminAccount: Audit
