providers: []
policySets:
  - deploymentTargets:
      organizationalUnits:
        - SomeEnv
        - Infrastructure
        - DataPlatfom
        - Security
    policies:
      - name: "{{ AcceleratorPrefix }}-CI-Role-Boundary-Policy"
        policy: iam-policies/ci-role-boundary-policy.json
  - deploymentTargets:
      organizationalUnits:
        - Root
    identityCenterDependency: true
    policies:
      - name: LZ-BP-Deafult-Boundary-Policy
        policy: iam-policies/default-sso-boundary-policy.json
roleSets:
  - deploymentTargets:
      organizationalUnits:
        - SomeEnv
        - Infrastructure
        - DataPlatfom
        - Security
    roles:
      - name: CI-Role
        assumedBy:
          - type: service
            principal: codebuild.amazonaws.com
        policies:
          awsManaged:
            - PowerUserAccess
        boundaryPolicy: "{{ AcceleratorPrefix }}-CI-Role-Boundary-Policy"
groupSets: []
userSets: []
identityCenter:
  name: blahblahexample
  delegatedAdminAccount: Audit
