defaultVpc:
  delete: false
  excludeAccounts: []
endpointPolicies:
  - name: Default
    document: vpc-endpoint-policies/default.json
  - name: EC2
    document: vpc-endpoint-policies/ec2.json
vpcs: []
transitGateways:
  - name: Network-Main
    account: Network
    region: ap-southeast-2
    shareTargets:
      organizationalUnits:
        - Infrastructure
    asn: 65521
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: disable
    autoAcceptSharingAttachments: enable
    routeTables:
      - name: Network-Main-Core
        routes: []
      - name: Network-Main-Segregated
        routes: []
      - name: Network-Main-Shared
        routes: []
      - name: Network-Main-Standalone
        routes: []
centralNetworkServices:
  delegatedAdminAccount: Network
  ipams:
    - name: "{{ AcceleratorPrefix }}-ipam"
      region: ap-southeast-2
      description: "{{ AcceleratorPrefix }} IPAM"
      operatingRegions:
        - ap-southeast-2
        - us-east-1
        - us-west-1
        - eu-central-1
        - eu-west-2    
      pools:
        ### Global Ipam Pools ###
        - name: "{{ AcceleratorPrefix }}-aws-pool"
          description: "Primary AWS IP Space."
          provisionedCidrs:
            - "{{ awsCidr }}"
        - name: "{{ AcceleratorPrefix }}-core-pool"
          description: "Core IP Space."
          locale: ap-southeast-2
          provisionedCidrs:
            - "{{ coreCidr }}"
          sourceIpamPool: "{{ AcceleratorPrefix }}-aws-pool"
        - name: "{{ AcceleratorPrefix }}-portal-pool"
          description: "Portal IP Space."
          locale: ap-southeast-2
          provisionedCidrs:
            - "{{ portalCidr }}"
          sourceIpamPool: "{{ AcceleratorPrefix }}-aws-pool"
        - name: "{{ AcceleratorPrefix }}-custom-pool"
          description: "Custom IP Space."
          locale: ap-southeast-2
          provisionedCidrs:
            - "{{ customCidr }}"
          sourceIpamPool: "{{ AcceleratorPrefix }}-aws-pool"
