homeRegion: &HOME_REGION {{ AcceleratorHomeRegion }}
#####################################
# Delete default VPCs-- use this    #
# object to delete default VPCs in  #
# any non-excluded accounts         #
#####################################
defaultVpc:
  delete: true
  excludeAccounts: []


transitGateways: []
vpcs: []


#####################################
# Transit Gateways-- use this object #
# to deploy transit gateways         #
#####################################
endpointPolicies:
  - name: Default
    document: vpc-endpoint-policies/default.json
  - name: Ec2
    document: vpc-endpoint-policies/ec2.json
