globalReplacements:
  # Accelerator Prefix
  - key: AcceleratorPrefix
    type: String
    value: testlz
  # Home Region
  - key: AcceleratorHomeRegion
    type: String
    value: ap-southeast-2
  # Security notification emails
  - key: SecurityHigh
    type: String
    value: someexamplelztest+new-securityhigh@gmail.com
  - key: SecurityMedium
    type: String
    value: someexamplelztest+new-securitymedium@gmail.com
  - key: SecurityLow
    type: String
    value: someexamplelztest+new-securitylow@gmail.com
  - key: SecurityIgnore
    type: String
    value: someexamplelztest+new-securityignore@gmail.com
  # Budget notification emails
  #- key: BudgetEmail
  #  type: String
  #  value: someexamplelztest+new-budget@gmail.com
  # Name of CloudWatch log group that centralizes CloudTrail logs. Referenced by CloudWatch metrics and alarms
  #- key: CloudTrailLogGroup
  #  type: String
  #  value: aws-controltower/CloudTrailLogs
  # Networking ranges
  # High level ranges
  - key: AwsCidr
    type: String
    value: 10.128.0.0/10
  - key: CoreCidr
    type: String
    value: 10.128.0.0/14
  - key: SomeEnvCidr
    type: String
    value: 10.132.0.0/15
  - key: SomeEnvProductionCidr
    type: String
    value: 192.168.0.0/24
  - key: SomeEnvStagingCidr
    type: String
    value: 192.168.1.0/24
  # - key: WorkloadInfrastructureCidr
  #  type: String
  #  value: 10.134.0.0/15
  - key: CustomerCidr
    type: String
    value: 10.136.0.0/13
  #  - key: OutsideAwsCidr
  #    type: String
  #    value: 10.0.0.0/9
  # - key: FutureUseCidr
  #   type: String
  #   value: 10.192.0.0/10
  - key: CentralEgressCidr
    type: String
    value: 10.128.0.0/18
  - key: CentralEgressTgwAzACidr
    type: String
    value: 10.128.0.0/24
  - key: CentralEgressTgwAzBCidr
    type: String
    value: 10.128.1.0/24
  - key: CentralEgressTgwAzCCidr
    type: String
    value: 10.128.2.0/24
  - key: CentralEgressNFAzACidr
    type: String
    value: 10.128.4.0/24
  - key: CentralEgressNFAzBCidr
    type: String
    value: 10.128.5.0/24
  - key: CentralEgressNFAzCCidr
    type: String
    value: 10.128.6.0/24
  - key: CentralEgressOutboundAzACidr
    type: String
    value: 10.128.8.0/24
  - key: CentralEgressOutboundAzBCidr
    type: String
    value: 10.128.9.0/24
  - key: CentralEgressOutboundAzCCidr
    type: String
    value: 10.128.10.0/24
  - key: OnPremisesPrefixList
    type: String
    value: 10.0.0.0/9
  # SomeEnv Development
  - key: SomeEnvDevelopmentCidr
    type: String
    value: 10.132.0.0/18
  #  - key: SomeEnvDevelopmentPublicCidr
  #    type: String
  #    value: 10.132.0.0/24
  - key: SomeEnvDevelopmentPublicAzACidr
    type: String
    value: 10.132.0.0/26
  - key: SomeEnvDevelopmentPublicAzBCidr
    type: String
    value: 10.132.0.64/26
  - key: SomeEnvDevelopmentPublicAzCCidr
    type: String
    value: 10.132.0.128/26
  #   Unallocated  from 10.132.1.0/24 -> 10.132.31.0/24
  #  - key: SomeEnvDevelopmentPrivateCidr
  #    type: String
  #    value: 10.132.32.0/19
  - key: SomeEnvDevelopmentPrivateAzACidr
    type: String
    value: 10.132.32.0/21
  - key: SomeEnvDevelopmentPrivateAzBCidr
    type: String
    value: 10.132.40.0/21
  - key: SomeEnvDevelopmentPrivateAzCCidr
    type: String
    value: 10.132.48.0/21
  # SomeEnv Staging
  - key: SomeEnvStagingCidr
    type: String
    value: 10.132.64.0/18
  - key: SomeEnvStagingPublicAzACidr
    type: String
    value: 10.132.64.0/26
  - key: SomeEnvStagingPublicAzBCidr
    type: String
    value: 10.132.64.64/26
  - key: SomeEnvStagingPublicAzCCidr
    type: String
    value: 10.132.64.128/26
  #  - key: SomeEnvStagingPrivateCidr
  #    type: String
  #    value: 10.132.96.0/19
  - key: SomeEnvStagingPrivateAzACidr
    type: String
    value: 10.132.96.0/21
  - key: SomeEnvStagingPrivateAzBCidr
    type: String
    value: 10.132.104.0/21
  - key: SomeEnvStagingPrivateAzCCidr
    type: String
    value: 10.132.112.0/21
  # SomeEnv Production
  - key: SomeEnvProductionCidr
    type: String
    value: 10.132.128.0/18
  - key: SomeEnvProductionPublicAzACidr
    type: String
    value: 10.132.128.0/26
  - key: SomeEnvProductionPublicAzBCidr
    type: String
    value: 10.132.128.64/26
  - key: SomeEnvProductionPublicAzCCidr
    type: String
    value: 10.132.128.128/26
  #  - key: SomeEnvProductionPrivateCidr
  #    type: String
  #    value: 10.132.160.0/19
  - key: SomeEnvProductionPrivateAzACidr
    type: String
    value: 10.132.160.0/21
  - key: SomeEnvProductionPrivateAzBCidr
    type: String
    value: 10.132.168.0/21
  - key: SomeEnvProductionPrivateAzCCidr
    type: String
    value: 10.132.176.0/21
