globalReplacements:
  # Accelerator Prefix
  - key: AcceleratorPrefix
    type: String
    value: lza
  # Home Region
  - key: AcceleratorHomeRegion
    type: String
    value: ap-southeast-2
  # Security notification emails
  - key: SecurityHigh
    type: String
    value: someexamplelztest+new-securityhigh@gmail.com
  - key: SecurityMedium
    type: String
    value: someexamplelztest+new-securitymedium@gmail.com
  - key: SecurityLow
    type: String
    value: someexamplelztest+new-securitylow@gmail.com
  - key: SecurityIgnore
    type: String
    value: someexamplelztest+new-securityignore@gmail.com
  # Budget notification emails
  #- key: BudgetEmail
  #  type: String
  #  value: someexamplelztest+new-budget@gmail.com
  # Name of CloudWatch log group that centralizes CloudTrail logs. Referenced by CloudWatch metrics and alarms
  #- key: CloudTrailLogGroup
  #  type: String
  #  value: aws-controltower/CloudTrailLogs
  # Networking ranges
  # High level ranges
  - key: AwsCidr
    type: String
    value: 172.16.0.0/12
  - key: CoreCidr
    type: String
    value: 172.16.0.0/16
  - key: SomeEnvCidr
    type: String
    value: 172.18.0.0/15
  - key: SomeEnvProductionCidr
    type: String
    value: 192.168.0.0/24
  - key: SomeEnvStagingCidr
    type: String
    value: 192.168.1.0/24
  - key: SomeEnvDevelopmentCidr
    type: String
    value: 192.168.2.0/24
  # - key: WorkloadInfrastructureCidr
  #  type: String
  #  value: 10.134.0.0/15
  - key: DataPlatfomCidr
    type: String
    value: 172.24.0.0/13
  #  - key: OutsideAwsCidr
  #    type: String
  #    value: 10.0.0.0/9
  # - key: FutureUseCidr
  #   type: String
  #   value: 10.192.0.0/10
  - key: CentralEgressCidr
    type: String
    value: 172.16.0.0/18
  - key: CentralEgressTgwAzACidr
    type: String
    value: 172.16.0.0/24
  - key: CentralEgressTgwAzBCidr
    type: String
    value: 172.16.1.0/24
  - key: CentralEgressTgwAzCCidr
    type: String
    value: 172.16.2.0/24
  - key: CentralEgressNFAzACidr
    type: String
    value: 172.16.4.0/24
  - key: CentralEgressNFAzBCidr
    type: String
    value: 172.16.5.0/24
  - key: CentralEgressNFAzCCidr
    type: String
    value: 172.16.6.0/24
  - key: CentralEgressOutboundAzACidr
    type: String
    value: 172.16.8.0/24
  - key: CentralEgressOutboundAzBCidr
    type: String
    value: 172.16.9.0/24
  - key: CentralEgressOutboundAzCCidr
    type: String
    value: 172.16.10.0/24
  - key: OnPremisesPrefixList
    type: String
    value: 172.0.0.0/8
  # SomeEnv Production
  - key: SomeEnvProductionCidr
    type: String
    value: 172.20.0.0/18
  - key: SomeEnvProductionPublicAzACidr
    type: String
    value: 172.20.0.0/26
  - key: SomeEnvProductionPublicAzBCidr
    type: String
    value: 172.20.0.64/26
  - key: SomeEnvProductionPublicAzCCidr
    type: String
    value: 172.20.0.128/26
  #  - key: SomeEnvProductionPrivateCidr
  #    type: String
  #    value: 10.132.160.0/19
  - key: SomeEnvProductionPrivateAzACidr
    type: String
    value: 172.20.8.0/21
  - key: SomeEnvProductionPrivateAzBCidr
    type: String
    value: 172.20.16.0/21
  - key: SomeEnvProductionPrivateAzCCidr
    type: String
    value: 172.20.24.0/21
