globalReplacements:
  # Accelerator Prefix
  - key: AcceleratorPrefix
    type: String
    value: testlz
  # Home Region
  - key: AcceleratorHomeRegion
    type: String
    value: ap-southeast-2
  # Security notification emails
  - key: SecurityHigh
    type: String
    value: bjsslztest+new-securityhigh@gmail.com
  - key: SecurityMedium
    type: String
    value: bjsslztest+new-securitymedium@gmail.com
  - key: SecurityLow
    type: String
    value: bjsslztest+new-securitylow@gmail.com
  - key: SecurityIgnore
    type: String
    value: bjsslztest+new-securityignore@gmail.com
  # Budget notification emails
  #- key: BudgetEmail
  #  type: String
  #  value: bjsslztest+new-budget@gmail.com
  # Name of CloudWatch log group that centralizes CloudTrail logs. Referenced by CloudWatch metrics and alarms
  #- key: CloudTrailLogGroup
  #  type: String
  #  value: aws-controltower/CloudTrailLogs
  # Networking ranges
  - key: AwsCidr
    type: String
    value: 10.128.0.0/10
  - key: CoreCidr
    type: String
    value: 10.128.0.0/14
  - key: PortalCidr
    type: String
    value: 10.132.0.0/14
  - key: CustomerCidr
    type: String
    value: 10.136.0.0/13
  - key: OnPremisesPrefixList
    type: String
    value: 192.168.0.0/16
