name: Unit Tests

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'tests/test_aws_checks.py'
      - 'preflight_checks/**'
  pull_request:
    paths:
      - 'tests/test_aws_checks.py'
      - 'preflight_checks/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run unit tests
        run: |
          pytest tests/test_aws_checks.py -v --cov=preflight_checks --cov-report=xml